### ISSUE TITLE
Border opacity not working

### ISSUE THREAD

**Issue by vltansky** [thibaudcolas/tailwindcss-vanilla-rtl#16]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/5851280/198667431-aeece63b-08f3-42b9-b06b-fe9a9e7fc473.png">

Commenting out borderOpacity fixes it. Probably cause plugins are added after the core plugins, so the opacity class is overridden by the default value. There is a possibility for similar bugs in other properties.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/5851280/198667643-f61493c3-f191-4b22-a814-442fc4006d92.png">
<img width="922" alt="image" src="https://user-images.githubusercontent.com/5851280/198667729-8919c1d0-690a-4c39-a9cb-d9d58e891b5d.png">

**Comment by thibaudcolas** [comment]
Nice catch @vltansky! I’ll work on a fix. This could indeed affect other properties – any that’s set by multiple plugins, where the CSS source order would be different between core plugins vs. this plugin.

Here are the properties I found used in multiple plugins:

- `margin` – used by `margin` and `space` core plugins. Shouldn’t cause issues since we’re overriding both.
- `margin` – this time used by `sr-only` and `container`. Shouldn’t cause issues because `sr-only` is before `margin` even in the corePlugins, and `container` is a component (so output after all utilities)
- `padding` – also used in `sr-only` and `container`. Also wouldn’t expect issues.
- border width – use by `borderWidth` and `divideWidth`. Same, shouldn’t cause issues since we’re overriding both.
- `--tw-border-opacity` – what this issue is about. Used by `borderOpacity` and `borderColor`
- `--tw-border-opacity` is also used inside the `visited:` variant of the `pseudoClassVariants` plugin. No idea whether that might cause issues, I suspect not but won’t check for now.

I’ll also update the docs to specify `vanillaRTL` should be the first entry inside the `plugins` array, as this would also be an issue if third-party plugins that produce utilities using the same properties were placed earlier in the `plugins`.
